### ISSUE TITLE
Doesn't look like npm:install is actually set up to run anything??

### ISSUE THREAD

**Issue by kobadg** [lorisleiva/laravel-deployer#109]
According to the npm bit, it doesn't show the install, and my build was actually failing during the install??

**Comment by lorisleiva** [comment]
Hi there 👋 

Can you please provide more information? What are your deployment logs and configurations?

**Comment by kobadg** [comment]
I'm not at my system right now, but I get mix is not found. Looking at my
deployed (it successfully deployed) files, there is no node_modules folder.

**Comment by lorisleiva** [comment]
If `mix` is not found then you likely have an issue with the way you import `laravel-mix`. Does this work on your local machine?

**Comment by kobadg** [comment]
Works locally.

Went to the deployed instance, tried running npm run dev, and got the
cross-env being not found(happens if npm install wasn't run first)

After manually doing an npm install on that release, doing npm run dev
worked fine and everything went as expected.

**Comment by kobadg** [comment]
Here is my .gitlab-ci.yml File
```
image: lorisleiva/laravel-docker:latest

.init_ssh: &init_ssh |
  eval $(ssh-agent -s)
  echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  ssh-keyscan -4 -p10022 staging.domain.com >> ~/.ssh/known_hosts
  chmod 644 ~/.ssh/known_hosts

.change_file_permissions: &change_file_permissions |
  find . -type f -not -path "./vendor/*" -exec chmod 664 {} \;
  find . -type d -not -path "./vendor/*" -exec chmod 775 {} \;

composer:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/
  script:
      - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
      - cp .env.example .env
      - php artisan key:generate
      - php artisan jwt:secret
  artifacts:
    expire_in: 1 month
    paths:
      - vendor/
      - .env

npm:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-npm
    paths:
      - node_modules/
  script:
      - npm install
      - npm run development
  artifacts:
    expire_in: 1 month
    paths:
      - node_modules/
      - public/css/
      - public/js/

staging:
  stage: deploy
  script:
    - *init_ssh
    - *change_file_permissions
    - php artisan deploy staging.domain.com -s upload
  environment:
    name: staging
    url: http://staging.domain.com
  only:
    - master
```
