### ISSUE TITLE
Build in gitlab pipeline

### ISSUE THREAD

**Issue by RosiersRobin** [lorisleiva/laravel-deployer#123]
I was wondering, how could you build the code in the gitlab pipeline? You can set the Default deployment strategy to "basic" to run all the builds etc... on the staging/production server and to "local" to build in the pipeline.

However, how can I make it build in the gitlab pipeline and then push it all to the server? (So I don't have to use the server to build and slow it down).

When I tried to set it to local, the gitlab runner can't clone the repo, snce I get permission denied. Is there a simple way to solve this problem?

The error I get:

```
Cloning into '/builds/rallypodium-reporting/rpr-site/vendor/lorisleiva/lara  
  vel-deployer/src/strategy/../../.build/releases/1'...                        
  Permission denied (publickey).                                               
  fatal: Could not read from remote repository.                                
                                                                               
  Please make sure you have the correct access rights                          
  and the repository exists.
```

**Comment by thomasaull** [comment]
@RosiersRobin I think you need to set a deploy key in your gitlab repository, this way deploy has pull access to your repo

**Comment by RosiersRobin** [comment]
@thomasaull I tried to do so, now I get `The command "which npm" failed.`, but on the runner I have a dependency of the `node:lts-alpine` image in the staging task (so where the deployment will hapen). Also on my server I (still) have node (and thus NPM) installed....

**Comment by fgilio** [comment]
Have you seen these 👇?
* https://lorisleiva.com/using-gitlabs-pipeline-with-laravel
* https://lorisleiva.com/laravel-deployment-using-gitlab-pipelines/

**Comment by thomasaull** [comment]
@RosiersRobin Are you building your assets in gitlab or on your server? For npm assets I usually have a pipeline job like this (pretty straightforward):

```
build:
  stage: build
  only:
    - master
  image: node:lts
  artifacts:
    paths:
      - dist
  script:
    - npm install
    - npm run build
```

Also the ressources @fgilio mentioned should be helpful :)

**Comment by RosiersRobin** [comment]
Force installing npm and node gives me

```
Error Output:                                                                
  ================                                                             
  sh: 1: cross-env: Permission denied                                          
  npm ERR! code ELIFECYCLE                                                     
  npm ERR! errno 126                                                           
  npm ERR! @ production: `cross-env NODE_ENV=production node_modules/webpack/  
  bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-m  
  ix/setup/webpack.config.js`                                                  
  npm ERR! Exit status 126                                                     
  npm ERR!                                                                     
  npm ERR! Failed at the @ production script.                                  
  npm ERR! This is probably not a problem with npm. There is likely additiona  
  l logging output above.                                                      
                                                                               
  npm ERR! A complete log of this run can be found in:                         
  npm ERR!     /root/.npm/_logs/2019-06-23T13_06_07_933Z-debug.log
```

**Comment by thomasaull** [comment]
@RosiersRobin Did you try using `image: node:lts` instead of alpine. I don't have to install npm at all!

**Comment by RosiersRobin** [comment]
This is my gitlab-ci config:

```
image: gitlab/dind:latest

stages:
  - preparation
  - building
  - testing
  - security
  - deploy-build
  - deploy

variables:
  CONTAINER_PHP_IMAGE: registry.gitlab.com/rallypodium-reporting/rpr-docker:latest
  CONTAINER_MYSQL_IMAGE: mysql:5.7
  CONTAINER_NODE_IMAGE: node:lts
  CONTAINER_DEPLOY_IMAGE: registry.gitlab.com/rallypodium-reporting/deployment:latest
  MYSQL_DATABASE: rpr
  MYSQL_ROOT_PASSWORD: toor
  DOCKER_DRIVER: overlay


##########################
## INSTALL DEPENDENCIES ##
##########################
composer:
  stage: preparation
  image: $CONTAINER_PHP_IMAGE
  services:
    - $CONTAINER_MYSQL_IMAGE
  before_script:
    - php -v # Have PHP version in logs
    - composer --version # Have Composer version in logs
    - git --version # Have Git version in logs
    - ls -lah # Overview of folders
    - cp -pRf .env.example .env
  script:
    - composer install --optimize-autoloader --prefer-dist --dev --no-suggest --no-interaction
  after_script:
    - php artisan key:generate
  artifacts:
    expire_in: 1hr
    paths:
      - ./.env
      - ./vendor
      - ./public/bundles

node:
  stage: preparation
  image: $CONTAINER_NODE_IMAGE
  before_script:
    - npm --version
  script:
    - npm install
  artifacts:
    expire_in: 1hr
    paths:
      - ./node_modules

########################
## BUILD DEPENDENCIES ##
########################
build-assets:
  stage: building
  image: $CONTAINER_NODE_IMAGE
  dependencies:
    - composer
    - node
  script:
    - npm run production
  artifacts:
    paths:
      - public/css/
      - public/js/
      - public/fonts/
      - public/admin
      - public/images
      - public/svg
      - public/mix-manifest.json
    expire_in: 1 days
    when: always

db-seeding:
  stage: building
  services:
    - $CONTAINER_MYSQL_IMAGE
  image: $CONTAINER_PHP_IMAGE
  dependencies:
    - composer
    - node
  script:
    - php artisan migrate:fresh --seed
  artifacts:
    paths:
      - ./storage/logs # for debugging
    expire_in: 1 days
    when: on_failure

####################
## CHECK THE CODE ##
####################
.test:
  stage: testing
  image: $CONTAINER_PHP_IMAGE
  dependencies:
    - build-assets
    - composer
    - db-seeding

lint:
  extends: .test
  script:
    - find app -type f -name "*.php" -exec php -l {} \;

codestyle:
  extends: .test
  script:
    - php vendor/bin/phpcs --standard=PSR2 --severity=error app

#phpunit:
#  extends: .test
#  services:
#    - $CONTAINER_MYSQL_IMAGE
#  script:
#    - ./vendor/phpunit/phpunit/phpunit --version
#    - php -d short_open_tag=off ./vendor/phpunit/phpunit/phpunit -v --colors=never --stderr
#  artifacts:
#    paths:
#      - ./storage/logs # for debugging
#    expire_in: 1 days
#    when: on_failure

phpcpd:
  extends: .test
  script:
    - test -f phpcpd.phar || curl -L https://phar.phpunit.de/phpcpd.phar -o phpcpd.phar
    - php phpcpd.phar app/ --min-lines=50
  cache:
    paths:
      - phpcpd.phar

####################
## SECURITY CHECK ##
####################
sensiolabs:
  stage: security
  image: $CONTAINER_PHP_IMAGE
  script:
    - test -d security-checker || git clone https://github.com/sensiolabs/security-checker.git
    - cd security-checker
    - composer install
    - php security-checker security:check ../composer.lock
  dependencies: []
  cache:
    paths:
      - security-checker/


#####################
## DEPLOY THE CODE ##
#####################
.init_staging_ssh: &init_staging_ssh |
  eval $(ssh-agent -s)
  echo "$SSH_PRIVATE_KEY_STAGING" | tr -d '\r' | ssh-add - > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

.init_production_ssh: &init_production_ssh |
  eval $(ssh-agent -s)
  echo "$SSH_PRIVATE_KEY_STAGING" | tr -d '\r' | ssh-add - > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

.change_file_permissions: &change_file_permissions |
  find . -type f -not -path "./vendor/*" -exec chmod 664 {} \;
  find . -type d -not -path "./vendor/*" -exec chmod 775 {} \;

# Staging deploy
staging:
  stage: deploy
  image: $CONTAINER_PHP_IMAGE
  environment:
    name: staging
    url: https://staging.rallypodium.be
  dependencies:
    - composer
    - node
  only:
    - development
  script:
    - *init_staging_ssh
    - *change_file_permissions
    - php artisan deploy staging -vvv

# Production deploy
production:
  stage: deploy
  image: $CONTAINER_DEPLOY_IMAGE
  environment:
    name: production
    url: https://www.rallypodium.be
  dependencies:
    - composer
    - node
  only:
    - master
  when: manual
  script:
    - *init_production_ssh
    - *change_file_permissions
    - php artisan deploy production
```
