### ISSUE TITLE
Upload strategy doesn't upload node_modules/ into my deployment with GitLab Pipelines

### ISSUE THREAD

**Issue by efraim14** [lorisleiva/laravel-deployer#155]
I have the same exact issue in #109 following your tutorial on: https://lorisleiva.com/laravel-deployment-using-gitlab-pipelines/

The main issue is, i need the `node_modules/` folder on my production, as it stated that `upload` strategy will never execute `hook:build`, how to include node_modules on my deployment?

Still a bit lost about the mechanism, as i still don't understand how all of my `css` and `js` from the `build` stage in GitLab is available on deployment, but not my node_modules. I've tried download my npm artifacts and it has `node_modules`, `public/css`, and `public/js` folder.

My GitLab CI: 

```
image: <laravel docker>

stages:
  - build
  - deploy
  
# The job's name.
composer:

  # The job's stage (build, test or deploy).
  stage: build
  # What to run on the job.
  script:
      - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
      - cp .env.example .env
      - php artisan key:generate

  artifacts:
    # (Optional) Give it an expiration date, 
    # after that period you won't be able to 
    # download them via the UI anymore.
    expire_in: 1 month
    # Define what to output from the job.
    paths:
      - vendor/
      - .env

  cache:
    # The variable CI_COMMIT_REF_SLUG 
    # refers to the slug of the branch.
    # For example: `master` for the master branch.
    # We use the `composer` suffix to avoid conflicts with
    # the `npm` cache that we'll define next.
    key: ${CI_COMMIT_REF_SLUG}-composer
    
    # Define what to cache.
    paths:
      - vendor/

npm:

  # Same stage as `composer` so that they run in parallel.
  stage: build
  
  # Cache the `node_modules` folder
  # using the `npm` suffix on the key.
  cache:
    key: ${CI_COMMIT_REF_SLUG}-npm
    paths:
      - node_modules/

  # Install and compile.
  script:
      - npm install
      - npm run production

  # Provide the other jobs of the pipeline with
  # the node dependencies and the compiled assets.
  artifacts:
    expire_in: 1 month
    paths:
      - node_modules/
      - public/css/
      - public/js/

      
.init_ssh: &init_ssh |
  eval $(ssh-agent -s)
  echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  ssh-keyscan <MY URL> >> ~/.ssh/known_hosts
  chmod 644 ~/.ssh/known_hosts

.change_file_permissions: &change_file_permissions |
  find . -type f -not -path "./vendor/*" -exec chmod 664 {} \;    
  find . -type d -not -path "./vendor/*" -exec chmod 775 {} \;

staging:
  stage: deploy
  script:
    - *init_ssh
    - *change_file_permissions
    - php artisan deploy <MY URL> -s upload
  environment:
    name: staging
    url: <MY URL>
  only:
    - master
```

Thank you before!
