### ISSUE TITLE
Strategy when using a CI/CD pipeline?

### ISSUE THREAD

**Issue by cviebrock** [lorisleiva/laravel-deployer#18]
First off, love this package.  Thank you!

I'm looking for a better way to deploy my Laravel apps using Gitlab's CI/CD pipelines.  My first stage is for testing and runs the following:

```
cp .env.example .env
composer install --prefer-dist --no-interaction --no-suggest --no-progress
npm install
npm run development
php artisan key:generate
php artisan migrate:refresh --seed
vendor/bin/phpunit -v
```

Assuming all tests pass, I'm left with a directory that doesn't really need anything done in it before deploying to my production server (except running `npm run production` to minify everything).

I tried with the `local` strategy, but that does a checkout of the repository again, re-runs all the composer/npm tasks, etc.., which adds unnecessary time.

Any suggestions on how to best do this?

**Comment by cviebrock** [comment]
For reference, here is my `gitlab-ci.yml` file:
```yaml
image: registry.gitlab.com/cviebrock/my-project:latest

variables:
  MYSQL_DATABASE: homestead
  MYSQL_ROOT_PASSWORD: secret
  DB_HOST: mysql
  DB_USERNAME: root

cache:
  untracked: true
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - vendor/
    - node_modules/

stages:
  - test
  - deploy

test:
  stage: test
  services:
    - mysql:5.7
  script:
    - cp .env.example .env
    - composer install --prefer-dist --no-interaction --no-suggest --no-progress
    - npm install
    - npm run development
    - php artisan key:generate
    - php artisan migrate:refresh --seed
    - vendor/bin/phpunit -v
  artifacts:
    paths:
      - ./storage/logs/*.log
    expire_in: 2 days
    when: always

deploy:
  stage: deploy
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - cp .env.example .env
    - composer install --prefer-dist --no-dev --no-interaction --no-suggest --no-progress
    - php artisan deploy
  environment:
    name: production
    url: http://192.168.1.1
  when: manual
  allow_failure: false
  only:
    - laravel5
```

And `config/deploy.php`:

```php
<?php

return [
    'default' => 'local',
    'strategies' => [
    ],
    'hooks' => [
        'start'   => [
        ],
        'build'   => [
            'npm:install',
            'npm:production',
        ],
        'ready'   => [
            'artisan:storage:link',
            'artisan:view:clear',
            'artisan:cache:clear',
            'artisan:config:cache',
            'artisan:optimize',
            'artisan:migrate',
        ],
        'done'    => [
        ],
        'success' => [
        ],
        'fail'    => [
        ],
    ],

    'options' => [
        'application'       => env('APP_NAME', 'Laravel'),
        'repository'        => 'git@gitlab.com:cviebrock/my-project.git',
        'branch'            => 'laravel5',
        'local_deploy_path' => '/tmp/my-project',
        'http_user'         => 'www-data',
        'local_upload_options' => [
            'options' => [
                '--exclude=".env.example"',
                '--exclude=".git/"',
                '--exclude=".gitattributes"',
                '--exclude=".gitignore"',
                '--exclude=".gitlab-ci.yml"',
                '--exclude="composer.json"',
                '--exclude="composer.lock"',
                '--exclude="Dockerfile"',
                '--exclude="node_modules/"',
                '--exclude="package-lock.json"',
                '--exclude="package.json"',
                '--exclude="phpunit.xml"',
                '--exclude="server.php"',
                '--exclude="storage/"',
                '--exclude="tests/"',
                '--exclude="vendor/"',
                '--exclude="webpack.mix.js"',
            ],
        ],
    ],
    'hosts' => [
        'new.my-project.com' => [
            'deploy_path' => '/var/www/my-project.com',
            'user'        => 'deployer',
            'port'        => 22,
        ],
    ],
    'localhost' => [
    ],
    'include' => [
    ],
    'custom_deployer_file' => false,
];
```

**Comment by lorisleiva** [comment]
Hey, I was actually thinking of doing a follow up blog article of [this one](http://lorisleiva.com/using-gitlabs-pipeline-with-laravel/) explaining how to deploy with GitLab. I haven't spent much time on it so your work is already very helpful thanks. 🙂 

Regarding your issue, I looks like you'd need to create a custom `gitlab` strategy that simply uploads without rebuilding locally (you can always run the `npm run production` on the gitlab job itself). Something like that:

![38677820-a775c720-3e5f-11e8-8d75-f0f3db60b246](https://user-images.githubusercontent.com/3642397/40958148-7d97bc48-6898-11e8-8cae-1987a809c329.png)

To create your custom strategy you'll can simply add it to your `strategies` option like this:

```php
'strategies' => [
    'gitlab' => [
        'hook:start',
        // Removed task local:build
        'deploy:prepare',
        'deploy:lock',
        'deploy:release',
        'deploy:update_code',
        'gitlab:upload', // New task gitlab:upload
        'deploy:shared',
        'firstdeploy:shared',
        'deploy:vendors',
        'deploy:writable',
        'hook:ready',
        'deploy:symlink',
        'deploy:unlock',
        'cleanup',
        'local:cleanup',
        'hook:done',
    ],
],
```

In order to create the new task, you'll have to [create a custom recipe](https://github.com/lorisleiva/laravel-deployer/blob/c95300309d0238699cf1176b5a8de5184c0217e5/docs/how-to-custom-recipes.md). You can then define it on there:

```php
desc('Upload your application built on gitlab to your hosts');
task('gitlab:upload', function () {
    $configs = array_merge_recursive(get('local_upload_options'), [
        'options' => ['--delete']
    ]);

    $local_path = __DIR__ . '/..';
    upload($local_path, '{{release_path}}', $configs);
});
```

I haven't tested all of that but that's the way I would go about implementing this. Let me know if this works for you and don't hesitate to share your results. I might even try to find a more generic way of solving this issue and provide it out of the box within the package.

**Comment by lorisleiva** [comment]
I've created a new `upload` strategy that simply uploads the content of your project folder to your host as a new release. It won't build anything since it assumes your project is ready to be live. I just need to document that strategy and I then I'll create a new release.

**Comment by cviebrock** [comment]
Awesome!  Based on the code you posted above, I've also got a successful build strategy working now.

FWIW, the relevant code in `config/deploy.php` is:

```php
    'strategies' => [
        'gitlab' => [
            'hook:start',
            'deploy:prepare',
            'deploy:lock',
            'deploy:release',
            'gitlab:upload',
            'deploy:shared',
            'firstdeploy:shared',
            'deploy:writable',
            'hook:ready',
            'deploy:symlink',
            'deploy:unlock',
            'cleanup',
            'local:cleanup',
            'hook:done',
        ],
    ],

...

    'options' => [
        'local_upload_options' => [
            'options' => [
                "--exclude='/.*'",
                "--exclude='/_ide_helper.php'",
                "--exclude='/composer.json'",
                "--exclude='/composer.lock'",
                "--exclude='/Dockerfile'",
                "--exclude='/node_modules/'",
                "--exclude='/package-lock.json'",
                "--exclude='/package.json'",
                "--exclude='/phpunit.xml'",
                "--exclude='/recipes/'",
                "--exclude='/server.php'",
                "--exclude='/storage/'",
                "--exclude='/tests/'",
                "--exclude='/webpack.mix.js'",
            ],
        ],
    ],

...

    'include' => [
        'recipes/gitlab.php',
    ],

```

And `recipies/gitlab.php`:

```php
<?php

namespace Deployer;

desc('Upload your application built on gitlab to your hosts');

task('gitlab:upload', function() {
    $local_path = __DIR__ . '/..';
    $configs = array_merge_recursive(get('local_upload_options'), [
        'options' => ['--delete'],
    ]);
    upload($local_path, '{{release_path}}', $configs);
});
```

And, for reference, `gitlab-ci.yml` is:

```yml
image: registry.gitlab.com/cviebrock/my_project:latest

variables:
  MYSQL_DATABASE: homestead
  MYSQL_ROOT_PASSWORD: secret
  DB_HOST: mysql
  DB_USERNAME: root

cache:
  untracked: true
  key: "vendors"
  paths:
    - vendor/
    - node_modules/

stages:
  - test
  - deploy

test:
  stage: test
  services:
    - mysql:5.7
  script:
    - cp .env.example .env
    - composer install --prefer-dist --no-interaction --no-suggest --no-progress
    - npm install
    - npm run development
    - php artisan key:generate
    - php artisan migrate:refresh --seed
    - vendor/bin/phpunit -v
  artifacts:
    paths:
      - ./storage/logs/*.log
    expire_in: 2 days
    when: always

deploy:
  stage: deploy
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - cp .env.example .env
    - composer install --prefer-dist --no-dev --no-interaction --no-suggest --no-progress --optimize-autoloader
    - npm run production
    - php artisan deploy
  environment:
    name: production
    url: http://192.168.1.1
  when: manual
  allow_failure: false
  only:
    - laravel5
```

**Comment by cviebrock** [comment]
Unrelated, I think ... all my directories are now chmod-ed `drwxrwxrwx` and files are `-rw-rw-rw-`.  Not sure if that's a side-effect of rsync, or how gitlab checks out the files into the Docker image (root user's umask is 0002, whereas the deployer user on my production server is 0022.

Any ideas?

**Comment by lorisleiva** [comment]
I have exactly the same problem at the moment. The permissions are already set like that on the Docker image before uploading:

<img width="524" alt="screen shot 2018-06-07 at 08 53 10" src="https://user-images.githubusercontent.com/3642397/41083031-72a875b8-6a30-11e8-99fd-c7fe9326c04a.png">

I am going to investigate that a bit more.

**Comment by lorisleiva** [comment]
It looks like they're still not sure about the right way to fix this because not fixing it means security issues but fixing it means breaking a lot of features.

In the mean time, a quick fix would be to change the permissions before uploading using:

```bash
find . -type f -not -path "./vendor/*" -exec chmod 664 {} \;    
find . -type d -not -path "./vendor/*" -exec chmod 775 {} \;
```

So the job would be something like that:

```yaml

staging:
  stage: deploy
  script:
    - *init_ssh
    - find . -type f -not -path "./vendor/*" -exec chmod 664 {} \;    
    - find . -type d -not -path "./vendor/*" -exec chmod 775 {} \;
    - php artisan deploy -s upload
  environment:
    name: staging
```

Alternatively, we could set the `GIT_STRATEGY` variable to `none` and clone it ourselves within the script of our jobs but I find it a bit more hacky than changing some permissions. I also like the fact that GitLab takes care of this for me.
