### ISSUE TITLE
Error Deploy to VPS.

### ISSUE THREAD

**Issue by hendisantika** [lorisleiva/laravel-deployer#215]
Error Deploy to VPS.

Using command `php artisan deploy ip-address -s upload`

I change hostname in :
```
staging:
  stage: deploy
  script:
    - *init_ssh
    - php artisan deploy dev.yourdomain.com -s upload
  environment:
    name: staging
    url: http://dev.yourdomain.com
  only:
    - master

```

Since I don't have any domain only IP Address so that I use IP Address that I got this error:

<img width="657" alt="image" src="https://user-images.githubusercontent.com/3713580/96570730-e3e9c280-12f4-11eb-8a8d-f8a02c2175ab.png">

https://gitlab.com/laravel-web-application/laravel-8-image-upload-with-preview

Do You have any advice?

Thanks
