### ISSUE TITLE
npm depends on .env entries - how to integrate in upload strategy?

### ISSUE THREAD

**Issue by simonbuehler** [lorisleiva/laravel-deployer#230]
hi,

when  using the gitlab ci and the pipeline from https://lorisleiva.com/laravel-deployment-using-gitlab-pipelines/ , now the js build depends on values in the .env file and the resulting `app.js` doesn't work on the deployed server.
I do have to do a `npm install && npm run prod` afterwards which defeats the whole idea of the deployer with upload strategy -  so whats the best practice here? 
Creating a .env.production which would differ from development .env somehow? please help, thanks!

**Comment by simonbuehler** [comment]
ok found a solution:

added a `.env.deploy` file to the repos which had all needed variables for production, then changed the npm part to

```
npm:
  # Same stage as `composer` so that they run in parallel.
  stage: build

  # Cache the `node_modules` folder
  # using the `npm` suffix on the key.
  cache:
    key: ${CI_COMMIT_REF_SLUG}-npm
    paths:
      - node_modules/

  # Install and compile.
  script:
    - cp .env.deploy .env
    - npm install
    - npm run production
```
and the js was correct and could be used in the upload strategy with out manually running `npm install && npm run prod` , works!
