### ISSUE TITLE
Question about .env after deploy (config:clear ?)

### ISSUE THREAD

**Issue by DevKylian** [lorisleiva/laravel-deployer#245]
When I do a deployment, the .env file is not taken into account I think?
I have to redo a "php artisan config:clear". 

I detected that when people who register do not receive the correct activation link:
Normally it is: https://mywebsite.com/activation/xxxxx
They receive : /activation/xxxxx

Knowing that https://mywebsite.com/ is an environment variable, I have to configure:clear manually after the deployment, do you have a solution?

Here is my deploy file:

```yaml
import:
  - recipe/laravel.php
  - contrib/php-fpm.php
  - contrib/npm.php

config:
  application: 'mywebsite.com'
  repository: 'git@github.com:DevKylian/mywebsite.com.git'
  php_fpm_version: '7.4'
  keep_releases: 3
  writable_dirs: [ "bootstrap/cache", "storage", "storage/app", "storage/framework", "storage/logs" ]

hosts:
  prod:
    remote_user: ubuntu
    hostname: mywebsite.com
    deploy_path: '/var/www/{{hostname}}'

tasks:
  deploy:
    - set:perms:before
    - deploy:prepare
    - deploy:vendors
    - artisan:storage:link
    - artisan:view:cache
    - artisan:config:clear
    - artisan:config:cache
    - artisan:migrate
    - npm:install
    - npm:run:prod
    - deploy:publish
    - set:perms:after
    - php-fpm:reload
  npm:run:prod:
    script:
      - 'cd {{release_path}} && npm rebuild && npm run prod'
  set:perms:before:
    script:
      - 'cd {{deploy_path}} && sudo chown -R ubuntu:www-data ../mywebsite.com/'
  set:perms:after:
    script:
      - 'cd {{deploy_path}} && sudo chown -R ubuntu:www-data {{deploy_path}}'
      - 'cd {{deploy_path}} && sudo find {{deploy_path}} -type f -exec chmod 664 {} \;'
      - 'cd {{deploy_path}} && sudo find {{deploy_path}} -type d -exec chmod 775 {} \;'
      - 'cd {{deploy_path}}/current && sudo chgrp -R www-data storage bootstrap/cache'
      - 'cd {{deploy_path}}/current && sudo chmod -R ug+rwx storage bootstrap/cache'

after:
  deploy:failed: deploy:unlock
```

While we're at it, if you notice any inconsistencies in my file, I'd appreciate any advice, thanks in advance
